FROM nginx:1.23.3-alpine

ADD ./nginx/nginx.conf /etc/nginx/nginx.conf
ADD ./nginx/.certs/localhost.crt /etc/nginx/certs/server.crt
ADD ./nginx/.certs/localhost.key /etc/nginx/certs/server.key

EXPOSE 80 443