services:
  nextjs:
    build:
      context: .
      platforms:
        - "linux/amd64"
      dockerfile: Dockerfile
    image: ${PROJECT}-${STAGE}-nextjs:latest
    container_name: nextjs
    ports:
      - "3000:3000"
    restart: always
  nginx:
    build:
      context: .
      platforms:
        - "linux/amd64"
      dockerfile: Dockerfile.nginx
    image: ${PROJECT}-${STAGE}-nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always