x-apps-config: &apps-env
  PROJECT: ${PROJECT:-qckstrt}
  NODE_ENV: ${NODE_ENV:-dev}
  AWS_PROFILE: ${AWS_PROFILE:-default}
  SECRETS: ${SECRETS:-secrets}

networks:
  frontend:
    name: ${PROJECT}-${NODE_ENV}-frontend
    external: false

services:
  nextjs:
    build:
      context: .
      platforms:
        - "linux/amd64"
      dockerfile: Dockerfile
    image: ${PROJECT}-${NODE_ENV}-nextjs:latest
    container_name: nextjs
    platform: "linux/amd64"
    networks:
      - frontend
    ports:
      - "3000:3000"
    restart: always
  nginx:
    build:
      context: .
      platforms:
        - "linux/amd64"
      dockerfile: Dockerfile.nginx
    image: ${PROJECT}-${NODE_ENV}-nginx:latest
    container_name: nginx
    platform: "linux/amd64"
    networks:
      - frontend
    ports:
      - "80:80"
      - "443:443"
    restart: always
