_format_version: "3.0"
consumers:
- hmacauth_credentials:
  - secret: '[CmyA!V<E5[g}rcp'
    username: postman-rodney
  username: postman-rodney
plugins:
- config:
    algorithms:
    - hmac-sha1
    - hmac-sha256
    - hmac-sha384
    - hmac-sha512
    anonymous: null
    clock_skew: 300
    enforce_headers: []
    hide_credentials: false
    realm: null
    validate_request_body: false
  enabled: true
  name: hmac-auth
  protocols:
  - grpc
  - grpcs
  - http
  - https
- config:
    cache_control: false
    cache_ttl: 30
    content_type:
    - application/json; charset=utf-8
    ignore_uri_case: false
    memory:
      dictionary_name: kong_db_cache
    request_method:
    - GET
    response_code:
    - 200
    response_headers:
      X-Cache-Key: true
      X-Cache-Status: true
      age: true
    storage_ttl: null
    strategy: memory
    vary_headers: null
    vary_query_params: null
  enabled: true
  name: proxy-cache
  protocols:
  - grpc
  - grpcs
  - http
  - https
- config:
    day: null
    error_code: 429
    error_message: API rate limit exceeded
    fault_tolerant: true
    header_name: null
    hide_client_headers: false
    hour: null
    limit_by: consumer
    minute: 60
    month: null
    path: null
    policy: local
    redis:
      database: 0
      host: null
      password: null
      port: 6379
      server_name: null
      ssl: false
      ssl_verify: false
      timeout: 2000
      username: null
    redis_database: 0
    redis_host: null
    redis_password: null
    redis_port: 6379
    redis_server_name: null
    redis_ssl: false
    redis_ssl_verify: false
    redis_timeout: 2000
    redis_username: null
    second: null
    sync_rate: -1
    year: null
  enabled: true
  name: rate-limiting
  protocols:
  - grpc
  - grpcs
  - http
  - https
services:
- connect_timeout: 60000
  enabled: true
  host: nestjs-api
  name: api
  path: /graphql
  port: 8080
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: api
    path_handling: v0
    paths:
    - /api
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
